apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: redhat-example-2
build:
  artifacts:
    - image: piomin/redhat-example-2
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}